name: Release
on:
  push:
    tags:
      - "n*"
  workflow_dispatch:

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yml
    secrets: inherit
  release:
    needs:
      - build-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AnyKernel3*
            realme_c35*
